[package]
name = "metatablesnow/issa"
description = "A runtime type validator with pretty errors and real types"
license = "MIT"
authors = ["metatablesnow"]
version = "0.2.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]